version: '3.8'

services:
<<<<<<< HEAD
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

=======
>>>>>>> dev
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "uptodate"
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
<<<<<<< HEAD
=======
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
>>>>>>> dev

  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/uptodate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
<<<<<<< HEAD
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
=======
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
>>>>>>> dev
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local